import { part1, part2 } from './day23';

const input1 = `.....
..##.
..#..
.....
..##.
.....`;

const input2 = `..............
..............
.......#......
.....###.#....
...#...#.#....
....#...##....
...#.###......
...##.#.##....
....#..#......
..............
..............
..............`;

describe('day 23, part 1', () => {
  it('should work with test input 1', () => {
    expect(part1(input1)).toBe(25);
  });

  it('should work with test input 2', () => {
    expect(part1(input2)).toBe(110);
  });
});

describe('day 23, part 2', () => {
  it('should work with test input', () => {
    expect(part2(input2)).toBe(20);
  });
});
